SHELL=/bin/bash
COLORTERM=truecolor
TERM_PROGRAM_VERSION=1.68.1
WSL_DISTRO_NAME=Ubuntu-20.04
NAME=Code
PWD=/home/bufallo/mio
LOGNAME=bufallo
VSCODE_GIT_ASKPASS_NODE=/home/bufallo/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/node
MOTD_SHOWN=update-motd
HOME=/home/bufallo
LANG=C.UTF-8
LS_COLORS=rs
GIT_ASKPASS=/home/bufallo/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=bufallo
VSCODE_GIT_IPC_HANDLE=/tmp/vscode-git-b47f25080d.sock
SHLVL=2
WSLENV=ELECTRON_RUN_AS_NODE/w:
VSCODE_GIT_ASKPASS_MAIN=/home/bufallo/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/extensions/git/dist/askpass-main.js
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/bufallo/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Python310/Scripts/:/mnt/c/Python310/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/Git/cmd:/mnt/c/composer:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/wamp64/bin/apache/apache2.4.51/bin:/mnt/c/wamp64/bin/php/php7.4.26:/mnt/c/wamp64/bin/mysql/mysql5.7.36/bin:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/LENOVO THINKPAD L390/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/LENOVO THINKPAD L390/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/LENOVO THINKPAD L390/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/LENOVO THINKPAD L390/AppData/Roaming/Composer/vendor/bin:/mnt/c/wamp64/bin/apache/apache2.4.51/bin:/mnt/c/wamp64/bin/mysql/mysql5.7.36/bin:/mnt/c/Users/LENOVO THINKPAD L390/AppData/Roaming/npm:/snap/bin
HOSTTYPE=x86_64
TERM_PROGRAM=vscode
VSCODE_IPC_HOOK_CLI=/tmp/vscode-ipc-b9aa9265-f2c1-4e69-81c9-402610f85f96.sock
_=./minishell
MESSI-1.0$ exit
